### ISSUE TITLE
Error: Class "Zend\Mail\Transport\Smtp" not found 

### ISSUE THREAD

**Issue by ciroTBB** [ebizmarts/magento2-mandrill-smtp#19]
Hello,

I ran a composer update and got the following error:

There is an error in vendor/ebizmarts/magento2-mandrillsmtp/Model/Transport/Smtp.php at line: 23
Class "Zend\Mail\Transport\Smtp" not found#0 vendor/composer/ClassLoader.php(571): include()
#1 vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists()
#4 setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass()
#5 setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract()
#6 setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList()
#7 setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation()
#8 setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(216): Magento\Setup\Module\Di\App\Task\Manager->process()
#9 vendor/symfony/console/Command/Command.php(298): Magento\Setup\Console\Command\DiCompileCommand->execute()
#10 vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#11 vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#12 vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun()
#13 vendor/symfony/console/Application.php(171): Magento\Framework\Console\Cli->doRun()
#14 bin/magento(23): Symfony\Component\Console\Application->run()
#15 {main}

It seems that "Laminas" is now used instead of "zendframework".

There is a Magento issue related to this: https://github.com/magento/magento2/issues/38421. Could you help me with this?

**Comment by gonzaloebiz** [comment]
Hi @ciromarano1905 

what version of magento are you using?

Best

**Comment by ciroTBB** [comment]
2.4.6-p3 and 102.3.4 of the plugin 

Sorry

**Comment by gonzaloebiz** [comment]
Try

composer require ebizmarts/magento2-mandrillsmtp:102.3.4

Best

**Comment by ciroTBB** [comment]
Hello Gonzalo, I already have that version, so the composer require didn't change anything. Are you asking me to run that command for a specific reason? What was the objective?

Regards!

**Comment by gonzaloebiz** [comment]
Take a look at https://github.com/ebizmarts/magento2-mandrill-smtp/commit/d1b286cbc3340c39adc0abee2f745e1d52305f2e and let me know if this fix your issue

Best

**Comment by ciromarano1905** [comment]
Hello, everything ok!

Thank you very much!

Greetings

**Comment by ciroTBB** [comment]
Everything ok Gonzalo, thank you very much. Are you going to include it in a future version?

Greetings.

**Comment by gonzaloebiz** [comment]
You already have a new version with the fix

Best
