### ISSUE TITLE
Emails not sending on M2.3.3 due to backward-incompatible changes

### ISSUE THREAD

**Issue by jaxtheking** [ebizmarts/magento2-mandrill-smtp#6]
This may strengthens the case I made here (#5) for the need of a Send Test Email function...
M2.3.3 introduced a backward-incompatible change by introducing the new `EmailMessageInterface`. You can read the relevant bit of the [release notes here](https://devdocs.magento.com/guides/v2.3/release-notes/release-notes-2-3-3-open-source.html#backward-incompatible-changes):

Therefore, the sending of emails in M2.3.3 results in the following error:
Fatal error: Uncaught TypeError: Argument 1 passed to `Ebizmarts\MandrillSmtp\Model\Transport\Smtp::sendMessage() must implement interface Magento\Framework\Mail\MessageInterface, instance of Magento\Framework\Mail\EmailMessage given, called in /vendor/ebizmarts/magento2-mandrillsmtp/Plugin/Mail/TransportPlugin.php on line 42 and defined in /vendor/ebizmarts/magento2-mandrillsmtp/Model/Transport/Smtp.php:48`

Stack trace:
`#0 /vendor/ebizmarts/magento2-mandrillsmtp/Plugin/Mail/TransportPlugin.php(42): Ebizmarts\MandrillSmtp\Model\Transport\Smtp->sendMessage(Object(Magento\Framework\Mail\EmailMessage))`

`#1 /vendor/magento/framework/Interception/Interceptor.php(135): Ebizmarts\MandrillSmtp\Plugin\Mail\TransportPlugin->aroundSendMessage(Object(Magento\Email\Model\Transport\Interceptor), Object(Closure))`

`#2 /dev/vendor/magento/module-email/Model/Mail/TransportInterfacePlugin.php(48): Mag in /dev/vendor/ebizmarts/magento2-mandrillsmtp/Model/Transport/Smtp.php on line 48`

To fix it, we just need to change all `MessageInterface` references (only 3) to `EmailMessageInterface` in /vendor/ebizmarts/magento2-mandrillsmtp/Model/Transport/Smtp.php, with no further changes needed.

I hope this helps.
Regards,
Luca

**Comment by gonzaloebiz** [comment]
Thanks @jaxtheking
